export let products=[{
  img: "chamille.jpg",
  name: "Chamomile Essential Oil",
  size: "5 ml",
  price: 56,
  description: "Roman chamomile is a perennial herbaceous plant that thrives in southern and central Europe. The Roman chamomile can grow up to 20 cm high and has white, aromatic flower heads. Chamomile has been around for Known to ancient times as a medicinal plant. In natural medicine, Roman chamomile is used for respiratory, stomach and intestinal problems as well as skin problems.",
  qtty: 1,
  availability: true
},
{
  img: "hellychrisum.jpg",
  name: "Helichrysum Essential Oil",
  size: "5 ml",
  price: 90,
  description: "Helichrysum, from the Greek “helios” for sun and “chrysos” for gold, is one of the world’s most sought-after essential oils. Native to coastal France, Italy, and Croatia, the delicate flowers bloom in rocky soils before a painstakingly careful harvest.Helichrysum has a unique chemistry that provides several skin care benefits, whether added to your facial moisturizer or applied directly to the skin as desired",
  qtty: 1,
  availability: false
},
{
  img: "lavander.jpg",
  name: "Lavander Essential Oil",
  size: "10 ml",
  price: 13,
  description: "Fine lavender, also called real lavender, is an aromatic herb that is native to the entire Mediterranean region. Lavender grows up to 1 meter high and the whole plant is highly aromatic. Lavender contains a Spectrum of over 100 ingredients and is considered the 'oil of the middle'; it is used in natural medicine for skin problems, insomnia, tension, muscle, digestive and respiratory problems. In gourmet cuisine it is used to delicately refine dishes and desserts and in It is a valued raw material in perfumery",
  qtty: 1,
  availability: true
},{
  img: "pepermint.jpg",
  name: "Spermit Essential Oil",
  size: "5 ml",
  price: 8,
  description: "Spearmint is a perennial medicinal and aromatic herb that prefers temperate climates. Spearmint can grow up to 80 cm high and has intensely fragrant leaves. It is used to flavor chewing gum, candies and Oral care products. In natural medicine, spearmint is used for stomach, cold and muscle problems",
  qtty: 1,
  availability: true},{
    img: "pine.jpg",
    name: "Pine Essential Oil",
    size: "5 ml",
    price: 12,
    description: "The Pine essential oil is distilled from branches of the Siberian fir (botanically: Abies sibirica). In our language, the oil is referred to as so-called “spruce needle oil”. The scent is woody-sweet, a typically fresh forest scent. The Siberian fir has a high proportion of monoterpene esters: This gives it a strong anxiety-relieving, relaxing effect. This essential oil is therefore ideal for stress and psychological imbalance.",
    qtty: 1,
    availability: true
  },{ 
  img: "rosmary.jpg",
  name: "Rosemary Essential Oil",
  size: "5 ml",
  price: 15,
  description: "Rosemary is an evergreen shrub, an ancient medicinal and spice plant that is native to the Mediterranean region and prefers chalky, sunny locations. Depending on the location, rosemary forms different chemotypes such as R. CT cineole or R. CT verbenone. In ancient times, rosemary was dedicated to Aphrodite and symbolized loyalty.",
  qtty: 1,
  availability: true},
  { img: "th.jpg",
  name: "Eucalyptus Essential Oil",
  size: "10 ml",
  price: 18,
  description: "Eucalyptus globulus is an evergreen hardwood tree native to Australia and Indonesia. Eucalyptus is one of the tallest trees and requires a lot of water, which is why it was often used to drain wetlands (and thus curb malaria), which gave it the name 'fever tree'. Not only in Australia, eucalyptus is part of the medicine cabinet for coughs and colds, skin problems, muscle and joint problems.",
  qtty: 1,
  availability: true},
  { img: "aria.jpg",
  name: "Aria Ultrasonic Diffuser",
  price: 150,
  description: "Aria Ultrasonic Diffuser is a unique, stylish way to bring the benefits of essential oils into your home or workplace. This attractive diffuser combines the latest in diffuser technology with a variety of useful features. The included remote lets you choose from a selection of soothing, built-in sounds or enjoy the multicolored LED lights. With the built-in speakers, you can plug in your own personal music device and enjoy the music of your choice.",
  qtty: 1,
  availability: true}, 
{img: "difussor3.jpg",
name: "Venera Ultrasonic Diffuser",
price: 30,
description: "Handcrafted with long-lasting natural ceramic materials, the Macaron Diffuser is a figurine art piece that blends seamlessly with your home or office décor. With its beautiful herringbone pattern, candlelight LED illumination and up to 16 hours run time —you’ll want one to cosy up every room!",
qtty: 1,
availability: true}]